const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'), vm=require('node:vm'), path=require('node:path');
const root=path.join(__dirname,'..');
const student=fs.readFileSync(path.join(root,'public/js/student-live.js'),'utf8'),teacher=fs.readFileSync(path.join(root,'public/js/teacher-live-v2.js'),'utf8'),server=fs.readFileSync(path.join(root,'server.js'),'utf8');
function extract(source,name){return source.match(new RegExp('^(?:async )?function '+name+'\\([^]*?^\\}','m'))[0]}
function sampleFixture(){const ctx={audioReceptionProgress:new Map(),window:{setTimeout,clearTimeout},Promise};vm.createContext(ctx);vm.runInContext(extract(student,'sampleAudioReception')+'\n'+extract(student,'audioPlaybackIsActive'),ctx);return ctx}
const track=()=>({id:'a',kind:'audio',readyState:'live',enabled:true,muted:false});
const stats=(bytes,samples)=>new Map([['audio',{type:'inbound-rtp',kind:'audio',bytesReceived:bytes,totalSamplesReceived:samples}]]);
test('Reception requires new inbound audio data and decoded samples, not permission or a live track',async()=>{const c=sampleFixture(),t=track();assert.equal(await c.sampleAudioReception('a',t,()=>stats(10,10)),false);assert.equal(await c.sampleAudioReception('a',t,()=>stats(20,20)),true);assert.equal(await c.sampleAudioReception('a',t,()=>stats(20,20)),false);assert.equal(await c.sampleAudioReception('a',t,()=>stats(30,20)),false);});
test('Muted and replaced tracks invalidate prior reception evidence',async()=>{const c=sampleFixture(),t=track();await c.sampleAudioReception('a',t,()=>stats(10,10));t.muted=true;assert.equal(await c.sampleAudioReception('a',t,()=>stats(20,20)),false);t.muted=false;assert.equal(await c.sampleAudioReception('a',t,()=>stats(30,30)),false);assert.equal(await c.sampleAudioReception('a',track(),()=>stats(40,40)),false);});
test('Playback confirmation rejects paused, muted, silent-volume and wrong-output elements',()=>{const c=sampleFixture(),t=track(),audio={paused:false,muted:false,volume:1,srcObject:{getAudioTracks:()=>[t]}};assert.equal(c.audioPlaybackIsActive(audio,t),true);for(const [key,value] of [['paused',true],['muted',true],['volume',0]]){assert.equal(c.audioPlaybackIsActive({...audio,[key]:value},t),false)}assert.equal(c.audioPlaybackIsActive({...audio,srcObject:{getAudioTracks:()=>[{id:'other'}]}},t),false)});
test('Teacher separates direct speaker reception from P2P mixture and expires stale reports',()=>{const ctx={attendeeElements:new Map([['speaker',{}],['direct',{}],['mix',{}],['unknown',{}]]),audioReceptionReports:new Map([['speaker',{receivedAt:10000,micPublished:true}],['direct',{receivedAt:10000,tracks:[{speakerSocketId:'speaker',confirmed:true}],p2pMixConfirmed:true}],['mix',{receivedAt:10000,tracks:[],p2pMixConfirmed:true}]]),Date};vm.runInNewContext(extract(teacher,'summarizeStudentAudioDelivery'),ctx);assert.deepEqual(JSON.parse(JSON.stringify(ctx.summarizeStudentAudioDelivery('speaker',10000))),{published:true,direct:1,mixed:1,waiting:1});assert.deepEqual(JSON.parse(JSON.stringify(ctx.summarizeStudentAudioDelivery('speaker',23000))),{published:false,direct:0,mixed:0,waiting:3})});
function serverFixture(){let handler;const emitted=[],socket={id:'listener',data:{role:'student',roomLevel:'room',studentId:'listener-id'},rooms:new Set(['room']),on(_event,fn){handler=fn}};const members=new Map([['listener',socket],['speaker',{data:{role:'student',roomLevel:'room',studentId:'speaker-id'}}],['closed',{data:{role:'student',roomLevel:'room',studentId:'closed-id'}}],['outsider',{data:{role:'student',roomLevel:'elsewhere',studentId:'outsider-id'}}]]);const ctx={socket,Date,activeTeachersByLevel:new Map([['room','teacher']]),isInLevelRoom:(s,l)=>s.rooms.has(l),isStudentMicrophoneOpen:(_l,id)=>id==='speaker',io:{sockets:{sockets:members,adapter:{rooms:new Map([['room',new Set(members.keys())]])}},to:id=>({emit:(name,data)=>emitted.push({id,name,data})})}};const start=server.indexOf('  socket.on("student_audio_reception_report",'),end=server.indexOf('  socket.on("student_media_transport_status",',start);vm.runInNewContext(server.slice(start,end),ctx);return {socket,handler,emitted}};
test('Server sends teacher only room-authorized speaker observations and checks playback',()=>{const f=serverFixture();f.handler({micPublished:true,tracks:[{identity:'speaker-id',receiving:true,playing:true},{identity:'closed-id',receiving:true,playing:true},{identity:'outsider-id',receiving:true,playing:true},{identity:'forged-id',receiving:true,playing:true}],p2pMix:{receiving:true,playing:false}});assert.equal(f.emitted.length,1);assert.equal(f.emitted[0].id,'teacher');assert.equal(f.emitted[0].data.micPublished,false);assert.equal(f.emitted[0].data.p2pMixConfirmed,false);assert.deepEqual(JSON.parse(JSON.stringify(f.emitted[0].data.tracks)),[{speakerSocketId:'speaker',confirmed:true}])});
test('Server rejects malformed reports, wrong roles, absent classroom membership and excessive reports',()=>{for(const bad of [null,{}, {tracks:Array(65).fill({})}]){const f=serverFixture();f.handler(bad);assert.equal(f.emitted.length,0)}for(const wrong of ['role','room']){const f=serverFixture();if(wrong==='role')f.socket.data.role='teacher';else f.socket.rooms.clear();f.handler({tracks:[]});assert.equal(f.emitted.length,0)}const f=serverFixture();f.handler({tracks:[]});f.handler({tracks:[]});assert.equal(f.emitted.length,1)});
test('Listener reports real SFU progression and cannot claim playback when paused',async()=>{let bytes=10;const t=track(),emitted=[],remote={mediaStreamTrack:t,getRTCStatsReport:()=>Promise.resolve(stats(bytes,bytes))},room={state:'connected',remoteParticipants:new Map([['speaker',{identity:'speaker-id',trackPublications:new Map([['audio',{track:remote}]])}]])};const ctx={audioReceptionProgress:new Map(),audioReceptionReportBusy:false,window:{setTimeout,clearTimeout},Promise,joinedClass:true,socket:{connected:true,emit:(_e,data)=>emitted.push(data)},studentSfuRoom:room,pc:null,teacherSocketId:'teacher',getSfuParticipantRole:()=> 'student',classmateAudioElements:new Map([['speaker-id',{paused:true,muted:false,volume:1,srcObject:{getAudioTracks:()=>[t]}}]]),teacherInboundAudioTrack:null,studentSfuMicPub:null,studentP2pMicSender:null,microphonePermissionGranted:false,getTeacherAudioElement:()=>null};vm.createContext(ctx);vm.runInContext(['sampleAudioReception','audioPlaybackIsActive','reportClassroomAudioReception'].map(n=>extract(student,n)).join('\n'),ctx);await ctx.reportClassroomAudioReception();bytes=20;await ctx.reportClassroomAudioReception();assert.equal(emitted[1].tracks[0].receiving,true);assert.equal(emitted[1].tracks[0].playing,false);ctx.classmateAudioElements.get('speaker-id').paused=false;bytes=30;await ctx.reportClassroomAudioReception();assert.equal(emitted[2].tracks[0].playing,true);assert.equal(emitted[2].micPublished,false)});

test('Unavailable or failed browser stats cannot create confirmed reception',async()=>{const c=sampleFixture(),t=track();assert.equal(await c.sampleAudioReception('a',t,null),false);assert.equal(await c.sampleAudioReception('a',t,()=>Promise.reject(new Error('unsupported'))),false);assert.equal(c.audioReceptionProgress.size,0)});
test('Teacher UI reports evidence counts and removes the label when microphone permission closes',()=>{let label=null;const attendee={querySelector:()=>label,append(node){label=node}};const ctx={attendeeElements:new Map([['speaker',attendee]]),approvedStudentMicrophones:new Set(['speaker']),audioReceptionReports:new Map(),summarizeStudentAudioDelivery:()=>({published:false,direct:0,mixed:2,waiting:3}),document:{createElement:()=>({remove(){label=null}})}};vm.runInNewContext(extract(teacher,'renderStudentAudioDeliveryStatus'),ctx);ctx.renderStudentAudioDeliveryStatus();assert.match(label.textContent,/بانتظار النشر/);assert.match(label.textContent,/استقبال صوته: 0/);assert.match(label.textContent,/استقبال المزيج: 2/);assert.match(label.textContent,/غير مؤكد: 3/);assert.match(label.title,/لا يثبت صوت هذا التلميذ/);ctx.approvedStudentMicrophones.clear();ctx.renderStudentAudioDeliveryStatus();assert.equal(label,null)});
