const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
const teacher=fs.readFileSync(path.join(root,'public/js/teacher-live-v2.js'),'utf8');
const student=fs.readFileSync(path.join(root,'public/js/student-live.js'),'utf8');
function fn(s,n){const m=s.match(new RegExp('^(?:async )?function '+n+'\\([^]*?^\\}','m'));assert.ok(m,n);return m[0];}
const quiet={info(){},warn(){},error(){},debug(){}};
function offerFixture(healthy=false){
 const video={kind:'video',readyState:'live',id:'screen'},audio={kind:'audio',readyState:'live'},senders=[];let offers=0;
 const peer={signalingState:'stable',connectionState:'connected',getSenders:()=>senders,addTrack(track){const s={track,async replaceTrack(next){this.track=next;}};senders.push(s);return s;},setConfiguration(){},async createOffer(){offers++;return{type:'offer',sdp:'video'};},async setLocalDescription(sdp){this.localDescription=sdp;this.signalingState='have-local-offer';}};
 const ctx={classActive:true,screenStream:{getVideoTracks:()=>[video]},getActiveTeacherVideoTrack:()=>video,getActiveTeacherAudioTrack:()=>audio,isTeacherSfuHealthy:()=>healthy,window:{},rtcConfig:{},peerConnections:{student:peer},createPeerConnection:()=>peer,closePeerConnection(){},ensureStudentAudioSender(p){if(!senders.some(s=>s.__classroomMixMinusAudio)){const s=p.addTrack(audio);s.__classroomMixMinusAudio=true;}},tuneOutboundSender(){},optimizeOpusSdp:s=>s,RTCSessionDescription:class{constructor(s){Object.assign(this,s)}},emitWithAcknowledgement:async()=>{},Date,console:quiet};
 vm.runInNewContext(['ensureTeacherVideoSender','flushPendingTeacherMediaOffer','createAndSendOffer'].map(n=>fn(teacher,n)).join('\n'),ctx);
 return{ctx,peer,senders,video,get offers(){return offers;}};
}
test('Late viewer forced to P2P receives current screen and audio even while teacher SFU is healthy',async()=>{const f=offerFixture(true);await f.ctx.createAndSendOffer('student',{force:true});assert.equal(f.offers,1);assert.equal(f.senders.find(s=>s.__classroomVideoTrack).track,f.video);assert.ok(f.senders.some(s=>s.track.kind==='audio'));});
test('Existing audio-only peer gets the already shared screen before its next offer',async()=>{const f=offerFixture();await f.ctx.createAndSendOffer('student');assert.equal(f.offers,1);assert.equal(f.senders.filter(s=>s.__classroomVideoTrack).length,1);});
test('Updating the screen replaces the video sender without duplicate senders',async()=>{const f=offerFixture();const old=f.peer.addTrack({kind:'video',readyState:'ended'});old.__classroomVideoTrack=true;await f.ctx.ensureTeacherVideoSender(f.peer);await f.ctx.ensureTeacherVideoSender(f.peer);assert.equal(old.track,f.video);assert.equal(f.senders.length,1);});
test('Screen added during pending negotiation is offered after the answer without waiting for another share',async()=>{const f=offerFixture();f.peer.signalingState='have-local-offer';f.peer.lastOfferSentAt=Date.now();await f.ctx.createAndSendOffer('student',{renegotiate:true});assert.equal(f.offers,0);assert.equal(f.peer.needsTeacherMediaOffer,true);f.peer.signalingState='stable';f.ctx.flushPendingTeacherMediaOffer('student',f.peer);await new Promise(r=>setImmediate(r));assert.equal(f.offers,1);assert.equal(f.peer.needsTeacherMediaOffer,false);});
test('Queued screen negotiation does not touch a replaced or closed peer',()=>{const f=offerFixture();const obsolete={needsTeacherMediaOffer:true,signalingState:'stable'};f.ctx.flushPendingTeacherMediaOffer('student',obsolete);assert.equal(f.offers,0);f.peer.needsTeacherMediaOffer=true;f.peer.signalingState='closed';f.ctx.flushPendingTeacherMediaOffer('student',f.peer);assert.equal(f.offers,0);});
test('Screen synchronization waits for SFU publication to finish before reporting its result',async()=>{const f=offerFixture(true);let release,finished=false;f.ctx.syncTeacherSfuMedia=()=>new Promise(r=>release=r);vm.runInNewContext(fn(teacher,'syncTeacherVideoTrackToAllPeers'),f.ctx);const p=f.ctx.syncTeacherVideoTrackToAllPeers().then(r=>{finished=true;return r;});await new Promise(r=>setImmediate(r));assert.equal(finished,false);release({success:true});assert.equal((await p).sfuResult.success,true);});
function monitorFixture(publications,screen=true){let tick,now=0,recovery=0;const room={state:'connected',remoteParticipants:new Map([['teacher',{trackPublications:new Map(publications)}]])};const ctx={studentSfuRoom:room,joinedClass:true,screenShareActive:screen,document:{visibilityState:'visible'},Date:{now:()=>now},setInterval(cb){tick=cb;return 1;},clearInterval(){},getSfuParticipantRole:()=> 'teacher',recordStudentDiagnosticEvent(){},notifySfuTransportStatus(){},clearStaleSfuMedia(){},disconnectStudentSfu(){ctx.joinedClass=false;},scheduleClassRecovery(){recovery++;}};vm.runInNewContext('let sfuReceptionMonitor=null;\n'+fn(student,'stopSfuReceptionMonitor')+'\n'+fn(student,'startSfuReceptionMonitor'),ctx);ctx.startSfuReceptionMonitor(room);return{ctx,room,tick:()=>tick(),time:n=>now=n,get recovery(){return recovery;}};}
test('Late viewer detects missing shared screen despite receiving teacher audio',async()=>{let bytes=0;const f=monitorFixture([['audio',{kind:'audio',track:{getRTCStatsReport:async()=>new Map([['r',{type:'inbound-rtp',bytesReceived:++bytes}]])}}]]);await f.tick();f.time(12000);await f.tick();assert.equal(f.recovery,1);});
test('Teacher present with no publications cannot indefinitely hide a missing shared screen',async()=>{const f=monitorFixture([]);await f.tick();f.time(12000);await f.tick();assert.equal(f.recovery,1);});
test('Intentional screen mute and adaptive pause do not cause missing-screen recovery',async()=>{for(const pub of [{kind:'video',isMuted:true},{kind:'video',track:{streamState:'paused'}}]){const f=monitorFixture([['video',pub]]);await f.tick();f.time(30000);await f.tick();assert.equal(f.recovery,0);}});
test('Old screen ending cannot stop its replacement',async()=>{let stopped=0,next=0;const streams=[0,1].map(i=>{const t={kind:'video',id:String(i),readyState:'live'};return{track:t,getVideoTracks:()=>[t],getTracks:()=>[{stop(){}}]};});const ctx={classActive:true,isEnding:false,sfuActiveForClass:false,screenStream:null,navigator:{mediaDevices:{getDisplayMedia:async()=>streams[next++]}},elements:{localVideo:{}},setStageMode(){},syncTeacherVideoTrackToAllPeers:async()=>({failed:0}),publishScreenShareState(){},addClassroomAudioSource(){},syncMixMinusAudioToAllPeers(){},setStudioStatus(){},updateControls(){},console:quiet,stopScreenShare(){stopped++;}};vm.runInNewContext(fn(teacher,'replaceScreenShareStream'),ctx);await ctx.replaceScreenShareStream();const oldEnd=streams[0].track.onended;await ctx.replaceScreenShareStream();oldEnd();assert.equal(stopped,0);streams[1].track.onended();assert.equal(stopped,1);});

 test('Targeted P2P viewer keeps receiving new screen offers when teacher SFU stays healthy',async()=>{const f=offerFixture(true);await f.ctx.createAndSendOffer('student',{force:true});assert.equal(f.peer.__teacherP2pFallback,true);f.peer.signalingState='stable';await f.ctx.createAndSendOffer('student',{renegotiate:true});assert.equal(f.offers,2);});
 test('Healthy SFU still avoids unsolicited duplicate P2P teacher offers',async()=>{const f=offerFixture(true);await f.ctx.createAndSendOffer('student');assert.equal(f.offers,0);assert.equal(f.senders.length,0);});
